@istest
public class BackupparalegalcntrlTest {
    @istest
    Public static void testmethod1(){
        
        
        string bc=Backupparalegalcntrl.getHiearchySettings();
        Backupparalegalcntrl.savedata('TEst');
        
        
    }
     @istest
    Public static void testmethod2(){
        
        string bc=NoticeOnHomepageCntrl.getconfidentilaitynotice();
        string bcc=NoticeOnHomepageCntrl.getPrivaynotice();
        NoticeOnHomepageCntrl.savedataCNnotice('Test');
        NoticeOnHomepageCntrl.savedataPrivacynotice('Test');
     
        
        
    }

}