@IsTest
public with sharing class MyTestClassTest {

 /*   @IsTest
    public static void testMyClass() {
//        cmpDocuSignOther.magicMethod();
//        DocumentDocuSignHelper.magicMethod();
//        DocumentDocuSignRecipient.magicMethod();
//        DocumentDocuSignResponse.magicMethod();



//        DocumentDocuSignService.magicMethod();
//        DocumentDocuSignSupplimentalAttachment.magicMethod();
//        DocuSignCreateApiAndSendDocument.magicMethod();
//        DocuSignReviewerSelector.magicMethod();

//        DocuSignEnvelopeController.magicMethod();
//        DocuSignEnvelopeSelector.magicMethod();
        DocuSignFutureWrapper.magicMethod();
//        DocuSignGenerateDocumentsForID.magicMethod();
//        DocuSignRecipientTriggerHelper.magicMethod();
//        DocuSignSendEnvelopeController.magicMethod();
//        insert new DocuSignEnvelope__c(Name = 'test');
        System.assert(true);

    }*/

}