public class RedirectionCtrl {
public PageReference init() {
        string url = 'https://aav0112.my.idaptive.app/applogin/appKey/eabdf64a-4618-41fa-92f5-e142b1e99f2e/customerId/AAV0112';
        PageReference page = new PageReference(url);
        page.setRedirect(true);
        return page;
    }

    public static void magicMethod() {
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;

    }



}