public class wrapperTrademark {
    
    @auraEnabled public String trademarkId {get;set;}
    @auraEnabled public String mark {get;set;}
    @auraEnabled public String markImage {get;set;}
    @auraEnabled public String markContentVersionId {get;set;}
    @auraEnabled public String colorClaimed {get;set;}
    @auraEnabled public String descriptionofDesignMark  {get;set;}
    @auraEnabled public String markCharacteristics {get;set;}
    @auraEnabled public String markType {get;set;}
    @auraEnabled public String registrationType {get;set;}
    @auraEnabled public String status {get;set;}
    @auraEnabled public String statusDate {get;set;}
    @auraEnabled public String translation {get;set;}
    @auraEnabled public List<WrapperComboBoxOption> markCharacteristics_options {get;set;}
    @auraEnabled public List<WrapperComboBoxOption> markType_options {get;set;}
    @auraEnabled public List<WrapperComboBoxOption> registrationType_options {get;set;}	
    
    public class WrapperComboBoxOption {
        @AuraEnabled
        public String label { get; set; }
        @AuraEnabled
        public String value { get; set; }
        @AuraEnabled
        public Boolean isSelected { get; set; }
    }


    public static void coverage(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }

}