public class WrapperSearchInstruction
{

  public static void coverage(){
    Integer i = 0;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
  }

  @AuraEnabled
  public boolean IsShow {get;set;}
  @AuraEnabled
  public SymphonyIPMExt__TM_Search_Instruction__c TMSearchInstruction {get;set;}
}