public class wrapperPillNew {
    
   @AuraEnabled
   public string type{get;set;}
   @AuraEnabled
   public string label{get;set;}
   @AuraEnabled
   public string name{get;set;}
   @AuraEnabled
   public string fallbackIconName{get;set;}
   @AuraEnabled
   public string variant{get;set;}
   @AuraEnabled
   public string alternativeText{get;set;}
   @AuraEnabled
   public string Recid{get;set;}
   @AuraEnabled
   public string EmailId{get;set;}
   @AuraEnabled
   public string InventorName{get;set;}
   @AuraEnabled
   public Boolean IsPrimary{get;set;}
   @AuraEnabled
   public string RoleOfConception{get;set;}
   @AuraEnabled
   public Integer IndexVal{get;set;}
   @AuraEnabled
   public Boolean IsActive{get;set;}
   @AuraEnabled
   public string UserId{get;set;}
   @AuraEnabled
   public string segment{get;set;}  
   @AuraEnabled
   public string comment{get;set;}  
    
}