public with sharing class WrapperRecommendationOpinion {

    public static void coverage(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }

    @AuraEnabled
    public Boolean IsShow {get;set;}

    @AuraEnabled
    public Recommendation_Opinion__c recommendationOpinion {get;set;}

    @AuraEnabled
    public Id recordId {get;set;}
}